# Generated by Django 6.0.4 on 2026-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('role_change', 'Role Changed'), ('export', 'Data Exported'), ('admin_action', 'Admin Action'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx')],
            },
        ),
    ]
