# Generated by Django 6.0.4 on 2026-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_user_id', models.IntegerField(db_index=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('notification_type', models.CharField(choices=[('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder_24h', 'Appointment Reminder (24h)'), ('appointment_reminder_1h', 'Appointment Reminder (1h)'), ('appointment_cancellation', 'Appointment Cancellation'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('no_show_followup', 'No-Show Follow-Up'), ('password_reset', 'Password Reset'), ('account_lockout', 'Account Lockout'), ('suspicious_login', 'Suspicious Login Alert'), ('welcome', 'Welcome'), ('billing_confirmation', 'Billing Confirmation'), ('billing_failed', 'Billing Payment Failed')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='queued', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['recipient_user_id', 'notification_type'], name='notificatio_recipie_1d8dd8_idx')],
            },
        ),
    ]
